"""retirando alguns termos

Revision ID: 99770fa4f1d1
Revises: b4c9548a34bf
Create Date: 2023-08-18 14:40:48.956352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99770fa4f1d1'
down_revision = 'b4c9548a34bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'cep')
    op.drop_column('usuario', 'status')
    op.drop_column('usuario', 'cpf')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('cpf', sa.VARCHAR(), nullable=True))
    op.add_column('usuario', sa.Column('status', sa.BOOLEAN(), nullable=True))
    op.add_column('usuario', sa.Column('cep', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
