"""adicionando produtos

Revision ID: 1739cb563648
Revises: b7b56fb1d60b
Create Date: 2023-09-08 11:17:52.642129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1739cb563648'
down_revision = 'b7b56fb1d60b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('avaliacao', sa.Float(precision=1), nullable=True))
    op.add_column('produto', sa.Column('descricao_detalhada', sa.String(length=2000), nullable=True))
    op.add_column('produto', sa.Column('qtd_estoque', sa.Integer(), nullable=True))
    op.drop_column('produto', 'detalhes')
    op.drop_column('produto', 'categoria')
    op.drop_column('produto', 'disponivel')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('disponivel', sa.BOOLEAN(), nullable=True))
    op.add_column('produto', sa.Column('categoria', sa.VARCHAR(), nullable=True))
    op.add_column('produto', sa.Column('detalhes', sa.VARCHAR(), nullable=True))
    op.drop_column('produto', 'qtd_estoque')
    op.drop_column('produto', 'descricao_detalhada')
    op.drop_column('produto', 'avaliacao')
    # ### end Alembic commands ###
