"""adicionar coluna de cpf

Revision ID: 2c23d603d4f5
Revises: 99770fa4f1d1
Create Date: 2023-08-23 14:02:04.532143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c23d603d4f5'
down_revision = '99770fa4f1d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('cpf', sa.String(length=11), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'cpf')
    # ### end Alembic commands ###
