"""Nova coluna categoria

Revision ID: 57724cdef239
Revises: 7487e8f6ab3d
Create Date: 2023-08-18 10:31:19.774254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57724cdef239'
down_revision = '7487e8f6ab3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produto', sa.Column('categoria', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produto', 'categoria')
    # ### end Alembic commands ###
