"""tabela de endereços ativar como principal

Revision ID: 6a6bc7e84633
Revises: c1b13a78ccdf
Create Date: 2023-10-18 11:21:09.228012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6bc7e84633'
down_revision = 'c1b13a78ccdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('endereco_entrega', sa.Column('is_principal', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('endereco_entrega', 'is_principal')
    # ### end Alembic commands ###
