"""modificando status

Revision ID: b7b56fb1d60b
Revises: 5b07a75bb47c
Create Date: 2023-08-28 15:01:13.300737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b56fb1d60b'
down_revision = '5b07a75bb47c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
